package com.comunidad.gestion.entity.enums;

public enum TipoAccionAuditoria {
    CREAR_USUARIO,
    MODIFICAR_USUARIO,
    LOGIN,
    LOGOUT,
    CREAR_COMUNERO,
    EDITAR_COMUNERO,
    CAMBIAR_ESTADO_COMUNERO,
    CAMBIAR_CONDICION_COMUNERO,
    CREAR_ASAMBLEA,
    EDITAR_ASAMBLEA,
    CAMBIAR_ESTADO_ASAMBLEA,
    REGISTRAR_ASISTENCIA,
    MODIFICAR_ASISTENCIA,
    CREAR_VOTACION,
    ABRIR_VOTACION,
    CERRAR_VOTACION,
    REGISTRAR_VOTO,
    CREAR_MULTA,
    GENERAR_MULTAS_MASIVAS,
    REGISTRAR_PAGO,
    CREAR_ACTA,
    EDITAR_ACTA,
    APROBAR_ACTA,
    MODIFICAR_CONFIGURACION
}
